
name: CI
on:
  workflow_dispatch:
  push:
env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.sec_token }}
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: 变量
        id: var
        run: sh test1.sh
        
      - name: 创建Release        
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: tag-${{ steps.var.outputs.da }}
          release_name: release-${{ steps.var.outputs.da }}
          draft: false
          prerelease: false
          body: |
            百度网址: ${{ steps.var.outputs.bdurl }}
          
      - name: 上传Release附件1
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ddd/1.jpg
          asset_name: 1.jpg
          asset_content_type: image/jpeg

      - name: 上传Release附件2
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ddd/2.txt
          asset_name: 2.txt
          asset_content_type: text/plain

      - name: 上传Release附件3
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ddd/3.zip
          asset_name: 3.zip
          asset_content_type: application/zip

