name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.sec_token }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        # set -x
        # assets=()
        # for asset in ./*.md; do
        #   assets+=("-a" "$asset")
        # done
        # tag_name="abcdef"
        # # hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        hub release create -a ./ddd/1.jpg -a ./ddd/2.txt -a ./ddd/3.zip -m "this is message" test12345


# jobs:
#   build:
#     runs-on: ubuntu-18.04
#     steps:
#       - uses: actions/checkout@v2

#       - name: 变量
#         id: var
#         run: sh test1.sh


      # - name: Create Release
      #   uses: actions/github-script@v2
      #   with:
      #     mytag: ${{ steps.var.outputs.da }}
      #     script: |
      #       console.log('environment', process.versions);
            
      #       const fs = require('fs').promises;
            
      #       // const { repo: { owner, repo }, sha } = context;
      #       console.log({ owner, repo, sha });

      #       const release = await github.repos.createRelease({
      #         owner, repo,
      #         tag_name: aaa,
      #         release_name: bb,
      #         draft: false,
      #         prerelease: false
      #       });

      #       console.log('created release', { release });
        
      #       for (let file of await fs.readdir('./ddd/')) {
      #         // do whatever filtering you want here, I'm just uploading all the files
      #         console.log('uploading', file);

      #         await github.repos.uploadReleaseAsset({
      #           owner, repo,
      #           release_id: release.data.id,
      #           name: file,
      #           data: await fs.readFile(`./ddd/${file}`)
      #         });            
      #       }

      # - name: 创建Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   with:
      #     tag_name: tag-${{ steps.var.outputs.da }}
      #     release_name: release-${{ steps.var.outputs.da }}
      #     draft: false
      #     prerelease: false
      #     body: |
      #       百度网址: ${{ steps.var.outputs.bdurl }}

      # - name: 上传Release附件1
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./ddd/1.jpg
      #     asset_name: 1.jpg
      #     asset_content_type: image/jpeg

      # - name: 上传Release附件2
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./ddd/2.txt
      #     asset_name: 2.txt
      #     asset_content_type: text/plain

      # - name: 上传Release附件3
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./ddd/3.zip
      #     asset_name: 3.zip
      #     asset_content_type: application/zip
